image: rustlang/rust:nightly-slim

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update && apt-get install -y nasm libfuse3-dev curl build-essential pkg-config libssl-dev
  - cargo install redoxer --locked
  - TARGET=${ARCH}-unknown-redox redoxer toolchain

stages:
  - host
  - build
  - test
  # TODO: benchmarks and profiling (maybe manually enabled for relevant MRs)?

build:
  stage: build
  script:
    - rustc --version
    - mkdir -p target/${ARCH}
    - TARGET=${ARCH}-unknown-redox redoxer env make BUILD=target/${ARCH}
  parallel:
    matrix:
      - ARCH: [x86_64, i686, aarch64, riscv64gc]

fmt:
  stage: host
  script:
      - rustup component add rustfmt-preview
      - cargo fmt -- --check

unit_test:
  stage: test
  script:
    - apt install -y qemu-system-x86 fuse3
    - TARGET=x86_64-unknown-redox redoxer test
