use super::number::*;

pub fn name(call: usize) -> &'static str {
    match call {
        SYS_LINK => "LINK",
        SYS_OPEN => "OPEN",
        SYS_CHMOD => "CHMOD",
        SYS_RMDIR => "RMDIR",
        SYS_UNLINK => "UNLINK",

        SYS_CLOSE => "CLOSE",
        SYS_DUP => "DUP",
        SYS_DUP2 => "DUP2",
        SYS_READ => "READ",
        SYS_WRITE => "WRITE",
        SYS_LSEEK => "LSEEK",
        SYS_FCNTL => "FCNTL",
        SYS_FEVENT => "FEVENT",
        SYS_FMAP => "FMAP",
        SYS_FUNMAP => "FUNMAP",
        SYS_FPATH => "FPATH",
        SYS_FSTAT => "FSTAT",
        SYS_FSTATVFS => "FSTATVFS",
        SYS_FSYNC => "FSYNC",
        SYS_FTRUNCATE => "FTRUNCATE",
        SYS_FUTIMENS => "FUTIMENS",

        SYS_BRK => "BRK",
        SYS_CHDIR => "CHDIR",
        SYS_CLOCK_GETTIME => "CLOCK_GETTIME",
        SYS_CLONE => "CLONE",
        SYS_EXECVE => "EXECVE",
        SYS_EXIT => "EXIT",
        SYS_FUTEX => "FUTEX",
        SYS_GETCWD => "GETCWD",
        SYS_GETEGID => "GETEGID",
        SYS_GETENS => "GETENS",
        SYS_GETEUID => "GETEUID",
        SYS_GETGID => "GETGID",
        SYS_GETNS => "GETNS",
        SYS_GETPID => "GETPID",
        SYS_GETPGID => "GETPGID",
        SYS_GETPPID => "GETPPID",
        SYS_GETUID => "GETUID",
        SYS_IOPL => "IOPL",
        SYS_KILL => "KILL",
        SYS_MKNS => "MKNS",
        SYS_NANOSLEEP => "NANOSLEEP",
        SYS_PHYSALLOC => "PHYSALLOC",
        SYS_PHYSFREE => "PHYSFREE",
        SYS_PHYSMAP => "PHYSMAP",
        SYS_PHYSUNMAP => "PHYSUNMAP",
        SYS_VIRTTOPHYS => "VIRTTOPHYS",
        SYS_PIPE2 => "PIPE2",
        SYS_SETPGID => "SETPGID",
        SYS_SETREGID => "SETREGID",
        SYS_SETRENS => "SETRENS",
        SYS_SETREUID => "SETREUID",
        SYS_SIGACTION => "SIGACTION",
        SYS_SIGRETURN => "SIGRETURN",
        SYS_WAITPID => "WAITPID",
        SYS_YIELD => "YIELD",

        _ => "?",
    }
}
